### ISSUE TITLE
Umlaut recurs and crashes prerender

### ISSUE THREAD

**Issue by sabrehagen** [prerender/prerender#219]
I've encountered an odd situation when trying to prerender the url `https://stemn.com/users/thomaspöschl6d`. The only thing I can see in the URL that would cause prerender to crash is the umlaut (ö). What's more interesting is that prerender seems to be continually adding umlauts in the same position on each subsequent attempt to prerender.

Here's my prerender server log:

2015-08-13T00:37:01.658Z getting bower_components/jquery/dist/jquery.min.map
2015-08-13T00:37:01.664Z getting bower_components/es5-shim/es5-shim.map
2015-08-13T00:37:01.754Z getting http://stemn.dev:3000/bower_components/angular-file-upload/angular-file-upload.min.map
2015-08-13T00:37:01.977Z got 504 in 319ms for bower_components/jquery/dist/jquery.min.map
2015-08-13T00:37:01.978Z got 504 in 314ms for bower_components/es5-shim/es5-shim.map
2015-08-13T00:37:02.030Z getting http://stemn.dev:3000/{{::image}}?size=feed-lg&crop=true
2015-08-13T00:37:02.252Z got 504 in 618ms for http://stemn.dev:3000/bower_components/es5-shim/es5-shim.map
2015-08-13T00:37:02.257Z got 504 in 621ms for http://stemn.dev:3000/bower_components/jquery/dist/jquery.min.map
2015-08-13T00:41:57.122Z getting https://stemn.com/users/timbroadbent79/followers?edit=false
2015-08-13T00:42:00.485Z got 200 in 3363ms for https://stemn.com/users/timbroadbent79/followers?edit=false
2015-08-13T00:42:50.859Z getting https://stemn.com/projects/pw-sat2-1u-cubesat?org=wolfgang
2015-08-13T00:44:41.126Z getting https://stemn.com/projects/pw-sat2-1u-cubesat?org=wolfgang
2015-08-13T00:44:46.940Z got 200 in 5814ms for https://stemn.com/projects/pw-sat2-1u-cubesat?org=wolfgang
2015-08-13T00:46:16.608Z getting https://stemn.com/users/thomaspöschl6d?org=unisec
2015-08-13T00:46:21.209Z getting https://stemn.com/users/thomaspÃ¶schl6d?org=unisec
2015-08-13T00:46:26.428Z getting https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:29.842Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:29.845Z got 504 in 13236ms for https://stemn.com/users/thomaspöschl6d?org=unisec
2015-08-13T00:46:29.875Z worker 3561 died, restarting!
2015-08-13T00:46:30.131Z starting phantom on port [12470]
2015-08-13T00:46:30.141Z Server running on port 3000
2015-08-13T00:46:30.299Z started phantom
2015-08-13T00:46:31.209Z getting https://stemn.com/users/thomaspÃ¶schl6d?org=unisec
2015-08-13T00:46:31.884Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:34.441Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:34.444Z got 504 in 13235ms for https://stemn.com/users/thomaspÃ¶schl6d?org=unisec
2015-08-13T00:46:34.479Z worker 3562 died, restarting!
2015-08-13T00:46:34.754Z starting phantom on port [12471]
2015-08-13T00:46:34.765Z Server running on port 3000
2015-08-13T00:46:34.930Z started phantom
2015-08-13T00:46:36.445Z getting https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:36.664Z getting https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:37.597Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:39.665Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:39.666Z got 504 in 13238ms for https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:39.696Z worker 3563 died, restarting!
2015-08-13T00:46:39.973Z starting phantom on port [12472]
2015-08-13T00:46:39.983Z Server running on port 3000
2015-08-13T00:46:40.152Z started phantom
2015-08-13T00:46:40.831Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:40.855Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:41.881Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:42.260Z getting https://stemn.com/users/thomaspÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:44.447Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:44.449Z got 504 in 13240ms for https://stemn.com/users/thomaspÃ¶schl6d?org=unisec
2015-08-13T00:46:44.481Z worker 3564 died, restarting!
2015-08-13T00:46:44.738Z starting phantom on port [12473]
2015-08-13T00:46:44.749Z Server running on port 3000
2015-08-13T00:46:44.914Z started phantom
2015-08-13T00:46:45.123Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:45.125Z got 504 in 13241ms for https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:45.159Z worker 3565 died, restarting!
2015-08-13T00:46:45.422Z starting phantom on port [12474]
2015-08-13T00:46:45.432Z Server running on port 3000
2015-08-13T00:46:45.596Z started phantom
2015-08-13T00:46:46.205Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:46.665Z getting https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:47.560Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:48.552Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:48.660Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:49.675Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:49.677Z got 504 in 13232ms for https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:49.721Z worker 3566 died, restarting!
2015-08-13T00:46:49.895Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:49.898Z got 504 in 13234ms for https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:49.930Z worker 3567 died, restarting!
2015-08-13T00:46:49.998Z starting phantom on port [12475]
2015-08-13T00:46:50.008Z Server running on port 3000
2015-08-13T00:46:50.172Z started phantom
2015-08-13T00:46:50.192Z starting phantom on port [12476]
2015-08-13T00:46:50.202Z Server running on port 3000
2015-08-13T00:46:50.370Z started phantom
2015-08-13T00:46:50.830Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:50.830Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:50.832Z got 504 in 13235ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:50.860Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:50.866Z worker 3568 died, restarting!
2015-08-13T00:46:51.124Z starting phantom on port [12477]
2015-08-13T00:46:51.134Z Server running on port 3000
2015-08-13T00:46:51.299Z started phantom
2015-08-13T00:46:51.945Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:52.270Z getting https://stemn.com/users/thomaspÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:52.947Z getting https://stemn.com/users/thomaspÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:54.056Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:54.059Z got 504 in 13228ms for https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:54.085Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:54.087Z got 504 in 13232ms for https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:54.098Z worker 3569 died, restarting!
2015-08-13T00:46:54.121Z worker 3557 died, restarting!
2015-08-13T00:46:54.388Z starting phantom on port [12479]
2015-08-13T00:46:54.394Z starting phantom on port [12478]
2015-08-13T00:46:54.399Z Server running on port 3000
2015-08-13T00:46:54.404Z Server running on port 3000
2015-08-13T00:46:54.561Z started phantom
2015-08-13T00:46:54.571Z started phantom
2015-08-13T00:46:55.114Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:55.116Z got 504 in 13235ms for https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:55.150Z worker 3558 died, restarting!
2015-08-13T00:46:55.173Z getting https://stemn.com/users/thomaspÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:55.408Z starting phantom on port [12480]
2015-08-13T00:46:55.418Z Server running on port 3000
2015-08-13T00:46:55.577Z started phantom
2015-08-13T00:46:55.993Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:56.766Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:57.929Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:58.555Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:58.624Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:46:59.896Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:46:59.899Z got 504 in 13234ms for https://stemn.com/users/thomaspÃÂ¶schl6d?org=unisec
2015-08-13T00:46:59.933Z worker 3559 died, restarting!
2015-08-13T00:47:00.201Z starting phantom on port [12481]
2015-08-13T00:47:00.211Z Server running on port 3000
2015-08-13T00:47:00.377Z started phantom
2015-08-13T00:47:01.789Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:01.790Z got 504 in 13238ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:01.829Z worker 3560 died, restarting!
2015-08-13T00:47:01.913Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:01.919Z got 504 in 13259ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:01.930Z getting https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:01.954Z worker 3570 died, restarting!
2015-08-13T00:47:02.088Z starting phantom on port [12482]
2015-08-13T00:47:02.097Z Server running on port 3000
2015-08-13T00:47:02.225Z starting phantom on port [12483]
2015-08-13T00:47:02.236Z Server running on port 3000
2015-08-13T00:47:02.255Z started phantom
2015-08-13T00:47:02.394Z started phantom
2015-08-13T00:47:04.068Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:04.076Z got 504 in 13246ms for https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:04.107Z worker 3571 died, restarting!
2015-08-13T00:47:04.359Z starting phantom on port [12484]
2015-08-13T00:47:04.368Z Server running on port 3000
2015-08-13T00:47:04.537Z started phantom
2015-08-13T00:47:05.161Z getting https://stemn.com/users/thomaspÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:05.184Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:05.190Z got 504 in 13245ms for https://stemn.com/users/thomaspÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:05.225Z worker 3572 died, restarting!
2015-08-13T00:47:05.478Z starting phantom on port [12485]
2015-08-13T00:47:05.488Z Server running on port 3000
2015-08-13T00:47:05.645Z started phantom
2015-08-13T00:47:06.740Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:07.940Z getting https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:09.229Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:09.235Z got 504 in 13242ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:09.267Z worker 3573 died, restarting!
2015-08-13T00:47:09.533Z starting phantom on port [12486]
2015-08-13T00:47:09.544Z Server running on port 3000
2015-08-13T00:47:09.709Z started phantom
2015-08-13T00:47:10.007Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:10.013Z got 504 in 13247ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:10.046Z worker 3574 died, restarting!
2015-08-13T00:47:10.314Z starting phantom on port [12487]
2015-08-13T00:47:10.324Z Server running on port 3000
2015-08-13T00:47:10.498Z started phantom
2015-08-13T00:47:11.425Z getting https://stemn.com/users/thomaspÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:15.905Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:18.392Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:18.398Z got 504 in 13237ms for https://stemn.com/users/thomaspÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:18.433Z worker 3575 died, restarting!
2015-08-13T00:47:18.705Z starting phantom on port [12488]
2015-08-13T00:47:18.716Z Server running on port 3000
2015-08-13T00:47:18.880Z started phantom
2015-08-13T00:47:19.974Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:19.980Z got 504 in 13240ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:20.012Z worker 3576 died, restarting!
2015-08-13T00:47:20.273Z starting phantom on port [12489]
2015-08-13T00:47:20.283Z Server running on port 3000
2015-08-13T00:47:20.453Z started phantom
2015-08-13T00:47:21.174Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:21.181Z got 504 in 13241ms for https://stemn.com/users/thomaspÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:21.215Z worker 3577 died, restarting!
2015-08-13T00:47:21.220Z getting https://stemn.com/users/thomaspÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:21.482Z starting phantom on port [12490]
2015-08-13T00:47:21.492Z Server running on port 3000
2015-08-13T00:47:21.651Z started phantom
2015-08-13T00:47:21.841Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:24.668Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:24.674Z got 504 in 13249ms for https://stemn.com/users/thomaspÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:24.705Z worker 3579 died, restarting!
2015-08-13T00:47:24.970Z starting phantom on port [12491]
2015-08-13T00:47:24.980Z Server running on port 3000
2015-08-13T00:47:25.142Z started phantom
2015-08-13T00:47:25.904Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:26.082Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:29.149Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:29.155Z got 504 in 13250ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:29.184Z worker 3578 died, restarting!
2015-08-13T00:47:29.419Z starting phantom on port [12492]
2015-08-13T00:47:29.428Z Server running on port 3000
2015-08-13T00:47:29.580Z started phantom
2015-08-13T00:47:32.034Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:35.075Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:35.081Z got 504 in 13240ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:35.116Z worker 3580 died, restarting!
2015-08-13T00:47:35.377Z starting phantom on port [12493]
2015-08-13T00:47:35.387Z Server running on port 3000
2015-08-13T00:47:35.551Z started phantom
2015-08-13T00:47:36.072Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:37.939Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:42.151Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:42.287Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:45.269Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:45.275Z got 504 in 13241ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:45.303Z worker 3581 died, restarting!
2015-08-13T00:47:45.569Z starting phantom on port [12494]
2015-08-13T00:47:45.579Z Server running on port 3000
2015-08-13T00:47:45.741Z started phantom
2015-08-13T00:47:47.726Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:48.168Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:48.362Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:49.313Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:49.319Z got 504 in 13247ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:49.349Z worker 3582 died, restarting!
2015-08-13T00:47:49.609Z starting phantom on port [12495]
2015-08-13T00:47:49.620Z Server running on port 3000
2015-08-13T00:47:49.799Z started phantom
2015-08-13T00:47:51.186Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:51.192Z got 504 in 13253ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:51.224Z worker 3583 died, restarting!
2015-08-13T00:47:51.497Z starting phantom on port [12496]
2015-08-13T00:47:51.508Z Server running on port 3000
2015-08-13T00:47:51.673Z started phantom
2015-08-13T00:47:52.153Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:52.260Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:52.376Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:53.806Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:54.367Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:55.382Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:55.388Z got 504 in 13237ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:55.421Z worker 3584 died, restarting!
2015-08-13T00:47:55.528Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:47:55.536Z got 504 in 13249ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:55.566Z worker 3585 died, restarting!
2015-08-13T00:47:55.690Z starting phantom on port [12497]
2015-08-13T00:47:55.699Z Server running on port 3000
2015-08-13T00:47:55.828Z starting phantom on port [12498]
2015-08-13T00:47:55.837Z Server running on port 3000
2015-08-13T00:47:55.866Z started phantom
2015-08-13T00:47:56.004Z started phantom
2015-08-13T00:47:57.066Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:58.169Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:58.360Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:47:58.493Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:00.119Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:00.956Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:00.962Z got 504 in 13236ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:00.996Z worker 3586 died, restarting!
2015-08-13T00:48:01.267Z starting phantom on port [12499]
2015-08-13T00:48:01.278Z Server running on port 3000
2015-08-13T00:48:01.401Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:01.408Z got 504 in 13240ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:01.441Z worker 3587 died, restarting!
2015-08-13T00:48:01.441Z started phantom
2015-08-13T00:48:01.595Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:01.602Z got 504 in 13240ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:01.638Z worker 3588 died, restarting!
2015-08-13T00:48:01.707Z starting phantom on port [12300]
2015-08-13T00:48:01.717Z Server running on port 3000
2015-08-13T00:48:01.900Z starting phantom on port [12301]
2015-08-13T00:48:01.903Z started phantom
2015-08-13T00:48:01.911Z Server running on port 3000
2015-08-13T00:48:02.074Z started phantom
2015-08-13T00:48:02.376Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:03.203Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:03.808Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:04.331Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:04.591Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:04.857Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:05.396Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:05.406Z got 504 in 13253ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:05.439Z worker 3589 died, restarting!
2015-08-13T00:48:05.612Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:05.617Z got 504 in 13241ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:05.649Z worker 3590 died, restarting!
2015-08-13T00:48:05.699Z starting phantom on port [12302]
2015-08-13T00:48:05.710Z Server running on port 3000
2015-08-13T00:48:05.878Z started phantom
2015-08-13T00:48:05.905Z starting phantom on port [12303]
2015-08-13T00:48:05.915Z Server running on port 3000
2015-08-13T00:48:06.130Z started phantom
2015-08-13T00:48:06.483Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:07.036Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:07.043Z got 504 in 13237ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:07.062Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:07.075Z worker 3591 died, restarting!
2015-08-13T00:48:07.339Z starting phantom on port [12304]
2015-08-13T00:48:07.349Z Server running on port 3000
2015-08-13T00:48:07.512Z started phantom
2015-08-13T00:48:08.468Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:08.971Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:11.401Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:11.407Z got 504 in 13238ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:11.441Z worker 3592 died, restarting!
2015-08-13T00:48:11.596Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:11.601Z got 504 in 13241ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:11.639Z worker 3593 died, restarting!
2015-08-13T00:48:11.709Z starting phantom on port [12305]
2015-08-13T00:48:11.719Z Server running on port 3000
2015-08-13T00:48:11.740Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:11.746Z got 504 in 13253ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:11.779Z worker 3594 died, restarting!
2015-08-13T00:48:11.893Z started phantom
2015-08-13T00:48:11.899Z starting phantom on port [12306]
2015-08-13T00:48:11.909Z Server running on port 3000
2015-08-13T00:48:12.045Z starting phantom on port [12307]
2015-08-13T00:48:12.055Z Server running on port 3000
2015-08-13T00:48:12.085Z started phantom
2015-08-13T00:48:12.220Z started phantom
2015-08-13T00:48:13.189Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:15.608Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:15.614Z got 504 in 13238ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:15.645Z worker 3595 died, restarting!
2015-08-13T00:48:15.915Z starting phantom on port [12308]
2015-08-13T00:48:15.925Z Server running on port 3000
2015-08-13T00:48:16.086Z started phantom
2015-08-13T00:48:16.441Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:16.448Z got 504 in 13245ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:16.487Z worker 3596 died, restarting!
2015-08-13T00:48:16.698Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:16.743Z starting phantom on port [12309]
2015-08-13T00:48:16.755Z Server running on port 3000
2015-08-13T00:48:16.922Z started phantom
2015-08-13T00:48:19.215Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:19.301Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:20.292Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:20.298Z got 504 in 13236ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:20.330Z worker 3597 died, restarting!
2015-08-13T00:48:20.597Z starting phantom on port [12310]
2015-08-13T00:48:20.608Z Server running on port 3000
2015-08-13T00:48:20.777Z started phantom
2015-08-13T00:48:21.707Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:21.714Z got 504 in 13246ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:21.756Z worker 3598 died, restarting!
2015-08-13T00:48:22.032Z starting phantom on port [12311]
2015-08-13T00:48:22.042Z Server running on port 3000
2015-08-13T00:48:22.217Z started phantom
2015-08-13T00:48:26.429Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:26.435Z got 504 in 13246ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:26.472Z worker 3599 died, restarting!
2015-08-13T00:48:26.734Z starting phantom on port [12312]
2015-08-13T00:48:26.744Z Server running on port 3000
2015-08-13T00:48:26.906Z started phantom
2015-08-13T00:48:29.284Z getting https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:29.927Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:29.934Z got 504 in 13236ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:29.966Z worker 3600 died, restarting!
2015-08-13T00:48:30.218Z starting phantom on port [12313]
2015-08-13T00:48:30.228Z Server running on port 3000
2015-08-13T00:48:30.390Z started phantom
2015-08-13T00:48:32.450Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:32.457Z got 504 in 13242ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:32.490Z worker 3601 died, restarting!
2015-08-13T00:48:32.746Z starting phantom on port [12314]
2015-08-13T00:48:32.756Z Server running on port 3000
2015-08-13T00:48:32.921Z started phantom
2015-08-13T00:48:42.524Z Experiencing infinite javascript loop. Killing phantomjs...
2015-08-13T00:48:42.530Z got 504 in 13246ms for https://stemn.com/users/thomaspÃÃÃÃÃÃÃÃÃÃÃÃÂ¶schl6d?org=unisec
2015-08-13T00:48:42.560Z worker 3602 died, restarting!
2015-08-13T00:48:42.803Z starting phantom on port [12315]
2015-08-13T00:48:42.813Z Server running on port 3000
2015-08-13T00:48:42.966Z started phantom

**Comment by thoop** [comment]
That's weird. Are you on the phantomjs2 branch? And which version of the prerender server are you seeing this on?

**Comment by sabrehagen** [comment]
This is on prerender 3.19.0 using phantom 0.7.2 and phantomjs 1.9.17.

**Comment by thoop** [comment]
Can you try 3.20.1? We pushed an encoding fix that might help here. You also might want to try PhantomJS 2 if that doesn't work.

**Comment by sabrehagen** [comment]
Upgrading to 3.20.1 didn't fix it. I'm compiling PhantomJS 2 from source now. I don't see any info in the prerender readme about running with PhantomJS 2. How would I run using PhantomJS 2?

**Comment by thoop** [comment]
You just need to checkout the phantomjs2 branch and then set your PHANTOMJS_CDNURL to point to the location of your compiled and zipped PhantomJS 2. Running an npm install should install PhantomJS 2 from that location and then everything else should work the same. Let me know if you have any issues!

**Comment by zhangfengGH** [comment]
Hi,how to set your PHANTOMJS_CDNURL??

**Comment by thoop** [comment]
@zhangfengGH you should export it on the command line like:
```
export PHANTOMJS_CDNURL=http://www.linktodirectory.com/
```
And then in that directory should live each PhantomJS 2 binary that you've compiled for different build systems (linux, osx, windows, etc).

**Comment by zhangfengGH** [comment]
@thoop  Dear，when I use PHANTOM_WORKER_ITERATIONS default Settings, phantomjs collapse often, but when I set PHANTOM_WORKER_ITERATIONS to a larger number of, say, 1000, and then collapse the number of times a lot less. Another problem is that, over time, the prerender with more memory, there seems to be a memory leak, is this why?

**Comment by thoop** [comment]
@zhangfengGH please open a new issue instead of hijaking this one. The number of iterations is how long before we forcibly shut down PhantomJS to prevent the memory leak issue. That's why you're seeing memory leaks when setting it to 1000. I wouldn't set it any higher than 200.

**Comment by thoop** [comment]
These issues shouldn't be a problem now with the latest version of Prerender (v4.0.3). Please upgrade and reopen if the issue persists.
