### ISSUE TITLE
5.21.1 unstable Chrome

### ISSUE THREAD

**Issue by breakiboy** [prerender/prerender#786]
Hi Guys,

Just switched from 5.20.2 to 5.21.1 and everything works fine until Chrome restarts after a while. Then Im facing only 504's. 
and some logs with Timed out waiting for chrome connections are visible. Do you have any tipps to fix this?

I falled back now again to 5.20.2 and it works again "ok". 

**OS**:
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Node.js version**       12.22.12
google-chrome-stable (124.0.6367.201-1)

**server.js**
#!/usr/bin/env node
var prerender = require('./lib');
const server = prerender({
  chromeFlags: ['--no-sandbox', '--headless', '--disable-gpu', '--remote-debugging-port=9222', '--hide-scrollbars', '--disable-dev-shm-usage'],
  forwardHeaders: true,
  chromeLocation: '/usr/bin/google-chrome',
  pageLoadTimeout: 20 * 1000,
});
server.use(require('prerender-disk-cache'));
server.use(prerender.sendPrerenderHeader());
server.use(prerender.browserForceRestart());
// server.use(prerender.blockResources());
server.use(prerender.addMetaTags());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
server.start();

**Comment by serjsv87** [comment]
clear install system
Similar problem
Everything works maybe 5-10 minutes and 10-15 requests and the next request is 504... (

my system

```bash
cat  /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

cat server.js 
#!/usr/bin/env node
var prerender = require('./lib');

var server = prerender({
        pageLoadTimeout: 1 * 2000,
        chromeLocation: '/usr/bin/chromium',
        chromeFlags: [
                '--disable-extensions',
                '--no-sandbox',
                '--headless',
                '--disable-gpu',
                '--disable-software-rasterizer',
                '--hide-scrollbars',
                '--remote-debugging-port=9222',
                '--skip-js-errors'
        ],
        workers: 4,
        logRequests: false
});
server.use(require('prerender-memory-cache'))
server.use(prerender.sendPrerenderHeader());
server.use(prerender.browserForceRestart());
// server.use(prerender.blockResources());
server.use(prerender.addMetaTags());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());

server.start();
```

**Comment by Ylmzef** [comment]
Is this bug still not fixed? I still have this problem with the system below.

Ubuntu = 20.04.6
chromium-browser = 126.0.6478.114
node v16.15.1
prerender@5.21.1

server.js
`const prerender = require('prerender');
const server = prerender({
    pageLoadTimeout: 1 * 2000,
    chromeLocation: '/usr/bin/chromium-browser',
    chromeFlags: [
        '--disable-extensions',
        '--no-sandbox',
        '--headless=new',
        '--disable-gpu',
        '--disable-software-rasterizer',
        '--hide-scrollbars',
        '--remote-debugging-port=9222',
        '--skip-js-errors',
        '--disable-dev-shm-usage',
        '--enable-logging',
        '--v=1'
    ],
    workers: 4,
    forwardHeaders: true,
    logRequests: false,
    logErrors: false
  });
  // server.use(require('prerender-memory-cache'))
  server.use(prerender.sendPrerenderHeader());
  server.use(prerender.browserForceRestart());
  // server.use(prerender.blockResources());
  server.use(prerender.addMetaTags());
  server.use(prerender.removeScriptTags());
  server.use(prerender.httpHeaders());
  
  server.start();`

**Comment by yojeek** [comment]
@breakiboy can you share the logs please?

**Comment by Ylmzef** [comment]
This issue still persists with version 5.21.4

**Comment by serjsv87** [comment]
Urs. Bat i think i find soluthion , docker compose down, remove valume
assets. Docker compose up.
But after i hame 500 if i try select projext. I change image to dev-slim,
after working

ср, 10 лип. 2024 р. о 04:13 Efex ***@***.***> пише:

**Comment by yojeek** [comment]
Should be fixed in `5.21.5` with https://github.com/prerender/prerender/pull/793.

**Comment by Ylmzef** [comment]
Hi @yojeek 

Unfortunately the problem still persists in version 5.21.5. After a while Chrome restarts and the problem goes away. However, during this time Google bot is encountering pages with 504 errors and this is a really serious problem for SEO.

**Comment by jcfjcosta** [comment]
> Hi @yojeek
> 
> Unfortunately the problem still persists in version 5.21.5. After a while Chrome restarts and the problem goes away. However, during this time Google bot is encountering pages with 504 errors and this is a really serious problem for SEO.

Hello,
We are having the same issue, prerender works fine for some hours and then it fails to connect to Chrome.
